# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_auto_20171207_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_hidden',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_on',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='price_override',
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='product.Category', verbose_name='companies'),
        ),
    ]
