# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_auto_20180125_1634'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='stock',
            name='location',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='productclass',
            name='is_shipping_required',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='StockLocation',
        ),
    ]
