# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_auto_20180125_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='file',
        ),
    ]
