# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_auto_20180126_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='file',
            new_name='image',
        ),
    ]
