# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-12 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='admin', max_length=64, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
