# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_auto_20180125_1634'),
        ('userprofile', '0015_auto_20171213_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='product.Category'),
        ),
    ]
