# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0017_auto_20180125_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='default_billing_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='default_shipping_address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
