# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-30 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180129_2018'),
        ('cart', '0002_auto_20180129_2018'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartuserfieldentry',
            unique_together=set([('cart', 'userfield')]),
        ),
    ]
