# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20171129_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='voucher',
        ),
    ]
