# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20180125_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='email',
        ),
    ]
