# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_auto_20171206_0506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverygroup',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AlterModelOptions(
            name='orderline',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_net',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_tax',
        ),
        migrations.RemoveField(
            model_name='order',
            name='voucher',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='delivery_group',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='stock_location',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='unit_price_gross',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='unit_price_net',
        ),
        migrations.AddField(
            model_name='order',
            name='employeeid',
            field=models.CharField(default='', max_length=256, verbose_name='employeeid'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
        migrations.AlterField(
            model_name='orderhistoryentry',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='comment'),
        ),
        migrations.DeleteModel(
            name='DeliveryGroup',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
