# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_auto_20180125_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='employeeid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='language_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_email',
        ),
    ]
