# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-28 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_auto_20180125_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Processing'), ('cancelled', 'Cancelled'), ('shipped', 'Shipped')], default='new', max_length=32, verbose_name='order status'),
        ),
        migrations.AlterField(
            model_name='orderhistoryentry',
            name='status',
            field=models.CharField(choices=[('new', 'Processing'), ('cancelled', 'Cancelled'), ('shipped', 'Shipped')], max_length=32, verbose_name='order status'),
        ),
    ]
